/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#343d96",
        "background": "#10141a",
        "primary": "#c3f5ff",
        "secondary-fixed-dim": "#bdc2ff",
        "surface-container": "#1c2026",
        "outline": "#849396",
        "on-secondary": "#1b247f",
        "tertiary-container": "#ffc2b3",
        "surface-container-low": "#181c22",
        "on-surface": "#dfe2eb",
        "on-primary": "#00363d",
        "primary-fixed-dim": "#00daf3",
        "on-tertiary": "#621100",
        "tertiary": "#ffe7e2",
        "surface-bright": "#353940",
        "on-primary-fixed": "#001f24",
        "secondary-fixed": "#e0e0ff",
        "primary-fixed": "#9cf0ff",
        "surface-variant": "#31353c",
        "on-secondary-container": "#a8afff",
        "surface-dim": "#10141a",
        "on-surface-variant": "#bac9cc",
        "outline-variant": "#3b494c",
        "surface-container-highest": "#31353c",
        "on-tertiary-fixed": "#3c0700",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0a0e14",
        "surface": "#10141a",
        "inverse-on-surface": "#2d3137",
        "surface-container-high": "#262a31",
        "on-tertiary-container": "#aa2600",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#004f58",
        "tertiary-fixed": "#ffdad2",
        "on-secondary-fixed": "#000767",
        "tertiary-fixed-dim": "#ffb4a2",
        "inverse-surface": "#dfe2eb",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#006875",
        "on-primary-container": "#00626e",
        "on-background": "#dfe2eb",
        "error-container": "#93000a",
        "secondary": "#bdc2ff",
        "on-tertiary-fixed-variant": "#8a1d00",
        "on-secondary-fixed-variant": "#343d96",
        "surface-tint": "#00daf3",
        "primary-container": "#00e5ff",
        // Keep semantic tokens for the backend mapping
        safe: '#10B981',
        'safe-dim': '#064E3B',
        warn: '#F59E0B',
        'warn-dim': '#451A03',
        danger: '#DC2626',
        'danger-dim': '#450A0A',
        cobalt: '#2563EB',
        'node-equipment': '#1D4ED8',
        'node-incident': '#B91C1C',
        'node-worker': '#475569',
        'node-zone': '#0F766E',
        'node-permit': '#B45309',
        'node-regulation': '#7C3AED',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
        display: ['"Chakra Petch"', 'sans-serif'],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      animation: {
        'critical-pulse': 'criticalPulse 1.5s ease-in-out infinite',
        'warn-pulse': 'warnPulse 2.5s ease-in-out infinite',
        'slide-in': 'slideIn 250ms ease-out',
        'fade-in': 'fadeIn 300ms ease-out',
      },
      keyframes: {
        criticalPulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.4' },
        },
        warnPulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
        slideIn: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(-8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
